[build-system]
requires = ["setuptools~=67.6.1", "wheel~=0.40.0", "Cython~=0.29.33"]
build-backend = "setuptools.build_meta"

[project]
name = "epunfold"
version = "0.2"
dependencies = ["networkx~=3.0", "pydot~=1.4.2"]

[project.scripts]
epunfold = "epunfold.__main__:_main"
